### ISSUE TITLE
rename error

### ISSUE THREAD

**Issue by stuta** [InCuca/vue-standalone-component#1]
...
   vue-cli · Generated "my-component".
   vue-cli · To get started:

fs.js:772
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: ENOENT: no such file or directory, rename 'src/Component/Component.vue' -> 'src/Component/my-component.vue'
    at Object.fs.renameSync (fs.js:772:18)

**Comment by klarkc** [comment]
Can you give me more information? I tried to reproduce without success. The steps to reproduce and the folder where you did the command can be useful

**Comment by klarkc** [comment]
Fixed, please reopen  if there you find more issues with renaming. Thank you
