### ISSUE TITLE
poi build to UMD doesnt minify the CSS properly

### ISSUE THREAD

**Issue by srini85** [InCuca/vue-standalone-component#15]
When we create a new component and add any inline styles to the file, the minified css file after a build seems to be **missing a trailing semi-colon** after each selector.

E.g. this is the sample my-component

```
<template lang="html">
  <strong>{{ text }}</strong>
</template>

<script>
/**
 * Component documentation
 */
export default {
  name: 'my-component',
  props: {
    /**
     * The component text
     */
    text: {
      type: String,
      default: '',
      required: true
    },
  },
}
</script>

<style lang="css" scoped>
  .test {
    color: red;
  }
</style>
```

run `npm run build`

goto the `dist\umd\my-component.min.css` file 

You get the following output (notice no semi colon after *red*) 

`
.test[data-v-4d6c94b0]{color:red}
/*# sourceMappingURL=my-component.min.css.map*/
`

This is on windows platform.

This is not a problem with this template or project but something to note in the poi component. I havent been able to trace the root cause yet, but would be good if anyone has any suggestions

**Comment by srini85** [comment]
I also created a standalone vue project using latest poi version (poi version 10). Ran a similar umd build and same issue.

Still trying to work out where in the process css from vue is stripped and minified.

**Comment by srini85** [comment]
Sorry this was my mistake.. I referenced in the file incorrectly on my html page.
Rather than using `<link>` i used `<script>`

**Comment by klarkc** [comment]
No problem, thanks for taking time to report! :+1:
